import "./globals.css";
import "bootstrap/dist/css/bootstrap.css";
import Head from "next/head";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (
    <html>
      <Head></Head>
      <body >
     {children}
      </body>
    </html>
  );
}
